### ISSUE TITLE
window.Testem.afterTests is causing a global failure

### ISSUE THREAD

**Issue by stevenwanderski** [percy/ember-percy#12]
The following line: https://github.com/percy/ember-percy/blob/master/addon/finalize.js#L18 is causing a global failure in the Ember test suite:

`Uncaught TypeError: Cannot read property 'afterTests' of undefined`

![image](https://cloud.githubusercontent.com/assets/473336/18961740/a029602a-8633-11e6-824c-d51f4e2b7993.png)

My stats: 
`Ember 2.4.6`
`Ember Data 2.7.0`

**Comment by fotinakis** [comment]
Hmm, it seems that `window.Testem` is not defined for you? Which is very odd, looking around for why this might be.

**Comment by fotinakis** [comment]
Figured it out, it's QUnit specific and only happens when you're visiting `/tests` directly, not in `ember test` mode.

Fixing here: https://github.com/percy/ember-percy/pull/13 and then will release a new version.

**Comment by fotinakis** [comment]
Deployed in v1.2.3, thanks for the report.

**Comment by amk221** [comment]
...I get this even in ember test mode
