### ISSUE TITLE
Autogenerated name for QUnit tests 

### ISSUE THREAD

**Issue by elidupuis** [percy/ember-percy#20]
We've been using `percySnapshot(assert);` to autogenerate the snapshot name in our tests and it's been working great. We're currently trying to upgrade to Ember 2.10 and our CI tests are filled with this error:

```
StatusCodeError: 400 - {"errors":[{"status":"bad_request"},{"source":{"pointer":"/data/attributes/base"},"detail":"The name of each snapshot must be unique, and this name already exists in the build: ...
```

Has anyone seen this before?

**Comment by fotinakis** [comment]
Hey @elidupuis — that's odd, what version of Ember are you upgrading from?

**Comment by elidupuis** [comment]
We're upgrading all the way from Ember 2.6.2. Looks like we're a patch version behind on ember-percy and a couple on ember-cli-qunit. I'll update those and ping back here if the issue persists.

**Comment by elidupuis** [comment]
@fotinakis I'm still seeing this error after upgrading both addons.

Is there a limit on the length of the test name? Our test name are quite long and the first portion is the same in some cases but they all have unique endings:

![image](https://cloud.githubusercontent.com/assets/196410/22613054/dd8b7b06-ea29-11e6-873d-c47446f0c174.png)

**Comment by fotinakis** [comment]
Hey @elidupuis, there is not a limit on name lengths (if given a large one, we hash it internally so we can handle effectively infinite-length unique names). I reached out to you in-app so we can debug this a bit more realtime, just login to Percy and you should see my message.
