### ISSUE TITLE
ember-component-css compatiblity

### ISSUE THREAD

**Issue by fotinakis** [percy/ember-percy#21]
For users using `ember-component-css`, integration tests apparently don't include the component styles, so the snapshot that Percy captures does not contain styles. This is not a Percy bug, but maybe there is a way we can make this easier / or documented?

Apparently the fix is needing `import 'dummy/initializers/component-styles';` in integration tests.

If anyone has an example addon/app that uses ember-component-css and is using Percy, would love to work with you to get this officially supported.

**Comment by rwwagner90** [comment]
@fotinakis any updates on this?

**Comment by Robdel12** [comment]
This shouldn't be an issue in v2 (with asset discovery rather than using the ember build system). Feel free to comment back if that's not the case 👍
