### ISSUE TITLE
"Error POSTing DOM" happening regularly

### ISSUE THREAD

**Issue by krasnoukhov** [percy/ember-percy#235]
Thanks to the merge of #234 we've been able to upgrade to the most recent Percy stack. However, I've noticed that our builds fail to create all snapshots with the log message originating here:

https://github.com/percy/ember-percy/blob/40cb769830e5688238c34ffa7b9f03b2d9e53d15/addon-test-support/%40percy/ember/index.js#L137

The message is like this:

> LOG: [percy] Error POSTing DOM, disabling: TypeError: Failed to fetch

This happened 3-4 times already on different builds since yesterday, including the baseline builds. This makes things really problematic since it results in "bad" baseline build, which in turn results in a lot of diffs for branch builds.

Here's a most recent example: https://percy.io/simplepractice/simplepractice/builds/7002777

Not sure where that error is coming from (percy agent?) but perhaps this addon can add a retry logic of sorts? Any update would be appreciated.

**Comment by krasnoukhov** [comment]
Any update on this? Still happening regularly.

**Comment by wwilsman** [comment]
Hey @krasnoukhov!

Are there any other logs in the browser console when you see that error? According to search results, that error comes from `fetch` when there is something up with the response and it seems like it is typically cors related. The local percy server uses a cors middleware to accept all requests, so I wonder what may be happening in your case.

**Comment by krasnoukhov** [comment]
Thanks for the reply. Seems like this happens when agent is not running due to this message:

> Warning: Skipping visual tests. PERCY_TOKEN was not provided

We have some conditions around `PERCY_TOKEN` which flake sometimes so that's the culprit. Sorry for the trouble
