### ISSUE TITLE
Type definition missing option

### ISSUE THREAD

**Issue by mfeckie** [percy/ember-percy#249]
https://github.com/percy/ember-percy/blob/master/types/index.d.ts#L5-L11

`percyCSS?: string` is missing from the available options

**Comment by mfeckie** [comment]
Would you folks be happy with a PR?

Secondly, would you folks be interested in having the addon converted to TypeScript so that types would be automatically kept in sync?

**Comment by Robdel12** [comment]
Hey @mfeckie! A PR would be great for the type update. We'll pass on converting to TS :)
