### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by mike-north** [percy/ember-percy#3]
Looks like we're starting two percy builds and finishing once, due to recent changes in the way an ember "fastboot build" is created

``` sh
# was
ember fastboot:build
# is now
ember build
```

Guards:

``` js
// node land
EMBER_CLI_FASTBOOT === 'true' // in fastboot mode
// browser land
typeof FastBoot === 'undefined' // not in fastboot mode
```

**Comment by fotinakis** [comment]
Thanks @mike-north for this and for the chat!

For reference, I cannot reproduce the fastboot double-build behavior we were seeing at all. Here is an ember-percy test run, with ember-cli-fastboot 1.0.0-beta.4, _without_ the `process.env. EMBER_CLI_FASTBOOT` check we added, and everything works fine:

https://travis-ci.org/percy/ember-percy/jobs/145164369

**Comment by fotinakis** [comment]
Closing stale issue.
