### ISSUE TITLE
Incorrect snapshotRoot when using an element as the scope

### ISSUE THREAD

**Issue by wwilsman** [percy/ember-percy#33]
[The change here](https://github.com/percy/ember-percy/pull/29/commits/bd8839fbf063d3f8f686f30e4c33fe9c7d05451f#diff-136d44d001d395cbcaa74fb6cd81f510R66) causes `snapshotRoot` to be an empty jQuery object when using an element as the `scope` option.

This happens because the element is a child of the original DOM and therefore not found in the `testingContainer` copy.

**Comment by Robdel12** [comment]
Heh 👋 

No longer valid since you pass a selector now 👍
