### ISSUE TITLE
Percy running for each Ember Try scenario 

### ISSUE THREAD

**Issue by elidupuis** [percy/ember-percy#4]
Just started using Percy (thanks so much!) and I'm wondering if there's a way to avoid diffing each scenario that Ember Try runs? 

I can see the benefit of running and diffing in every scenario but I can also see wanting to only run in the default scenario. Any thoughts?

**Comment by fotinakis** [comment]
Hey @elidupuis! Yes, you can set the `PERCY_ENABLE=0` environment variable to disable it. For example, we do this for the ember-percy addon itself in our travis.yml: https://github.com/percy/ember-percy/blob/master/.travis.yml#L14

So the best way to do this would be to set `PERCY_ENABLE=0` by default in your test environment, and then set `PERCY_ENABLE=1` for the one ember-try scenario you want visual coverage for.

Let me know if that doesn't work!

**Comment by elidupuis** [comment]
Oh, awesome! I'll give that a try. Thanks!

**Comment by Robdel12** [comment]
Hey @amyrlam! You would want to toggle `PERCY_ENABLE` for each job in the matrix here: https://github.com/hashicorp/design-system/blob/main/.github/workflows/ci-components.yml#L87-L89 You'd look at `${{ matrix.try-scenario }}` and decide if you wanted to set `PERCY_ENABLE` to `1` or `0`

**Comment by amyrlam** [comment]
@Robdel12 thank you, I'm sorted! (For some reason I still find GitHub Actions a lot more confusing than Travis)
