### ISSUE TITLE
Percy forever waiting on snapshot to be uploaded

### ISSUE THREAD

**Issue by MondeSameWave** [percy/ember-percy#5]
Building a ember 2.5 app. Testing with travis with parallel test suits. I've configured pretender to let percy through `this.post('/_percy/:path', this.passthrough);` and added the environment variable `PERCY_PARALLEL_TOTAL=2` in travis. 

I've only added one snapshot to a test. All tests pass on travis but percy is hanging.
The "Waiting for snapshot uploads... " message is displayed.

Test also run locally without error.

**Comment by fotinakis** [comment]
How are your tests parallelized?

**Comment by fotinakis** [comment]
I just checked in the database, and there were no snapshots uploaded for any of the builds pushed to your repo at all. This very likely means that the pretender config is not correct. I don't know of a great way to debug this, other than running in `ember test --server` — open up the Inspector in the browser, then refresh the page to run your tests again. Do you see an error about network requests being blocked?

**Comment by fotinakis** [comment]
@MondeSameWave — I now have a few different fixes for this particular issue, depending on what it actually is for you (there is a Pretender shutdown bug that may cause this), and/or some parallelization issues.

If you come back to this, let me know and I can help you debug! Feel free to reach out in the app as well.
