### ISSUE TITLE
Invalid URL or path when running separate build and test steps

### ISSUE THREAD

**Issue by adamhong** [percy/ember-percy#51]
In our CI setup, we have separate build + test steps: https://percy.io/docs/clients/javascript/ember#separate-build-and-test-steps

When actually running the test steps, I am seeing the following error:

```
[percy][ERROR] API call failed, Percy has been disabled for this build.
StatusCodeError: 400 - {"errors":[{"status":"bad_request","detail":"Invalid URL or path: undefined/<FILENAME>"}]}
```

Tracked this down to the following:

https://github.com/percy/ember-percy/blob/master/index.js#L51

`normalizedRootUrl` is undefined at runtime when running build + tests separately. It appears that the `config` method is not called before in this scenario.

**Comment by adamhong** [comment]
appears to be another issue, possibly misconfiguration. seeing the same thing running build + tests together. will update with resolution

**Comment by timhaines** [comment]
@adamhong could you possibly provide us with a simple reproduction?

**Comment by adamhong** [comment]
@timhaines yes, sorry for delayed response. i'll update with repro steps. thanks!

**Comment by fotinakis** [comment]
@adamhong we have another customer who we believe hit this same issue. Could you send us your `ember build --environment=test` and `ember exam ...` commands from your package.json so we can see if there's some specific configuration you're using there that might cause this? We do a similar split build/test steps but haven't encountered this issue ourselves.
