### ISSUE TITLE
HTML/CSS inconsistency when running percy on Travis CI

### ISSUE THREAD

**Issue by drogus** [percy/ember-percy#52]
We're using Percy.io to test https://github.com/travis-ci/travis-web and we're seeing an inconsistency between what's displayed when running tests and what gets uploaded to Percy. At first my thought was that there's a difference between the VM on which we're running the tests, but today I ran the tests in debug mode in Chrome running inside Xvfb and I got a screenshot, which indicates that the tests look OK. The problem exists only in the profile page. Here's how it looks like in production right now:

<img src="https://cl.ly/2t03292w3a0U/Image%202018-02-09%20at%2011.56.23%20AM.png" width=300 />

Here's what percy snapshots:

<img src="https://cl.ly/132w2m3h2w1Z/Image%202018-02-09%20at%2011.58.13%20AM.png" width=300 />

And here's a snapshot from the Travis CI's VM: https://transfer.sh/117ixF/foo.jpg

I'll be looking more into this issue, but if you want to try to reproduce this, you can clone the travis-web repo and run tests with `ember test --filter "view profile"`. Let me know if you need any more details.

**Comment by fotinakis** [comment]
Hey @drogus — sorry for the delay here. If you're still experiencing this issue, please reach out to us in our Intercom chat and we can dig into this with you.
