### ISSUE TITLE
consider using addon-test-support/ instead of test-support/

### ISSUE THREAD

**Issue by nruth** [percy/ember-percy#79]
While researching how to use this with the new ember qunit layout I came across another issue in https://dockyard.com/blog/2018/01/18/test-helpers-the-next-generation about the new file layout issue.  (attached as image to preserve layout).

It may be worth moving the helper file path to this namespaced location when there's going to be a major version bump.

Excerpt follows:

![screen shot 2018-10-21 at 17 28 05](https://user-images.githubusercontent.com/26158/47269514-b5467f00-d556-11e8-9efc-29f16accb883.png)

**Comment by Robdel12** [comment]
Taken care of with #163 (v2) 🎉
