### ISSUE TITLE
In new style (RFC-232) tests, async helpers should return a promise that can be awaited.

### ISSUE THREAD

**Issue by Gaurav0** [percy/ember-percy#80]
Related to #60 

In RFC-232 style tests, a helper such as percySnapshot registered as an async helper is responsible for returning a promise. Users are responsible for awaiting that promise. "Magic" auto-promise-like behavior is discouraged.

**Comment by jeanduplessis** [comment]
We're trying to upgrade to the latest Ember 3.8 release but using the percySnapshot method directly as per the recommendation in this comment, https://github.com/percy/ember-percy/issues/60#issuecomment-375083787, no longer works. The Percy build doesn't seem to receive the data anymore. I tried doing an `await settled()` after calling the snapshot to see if it would help but it didn't. 

Only way really forward that I can see is for the percySnapshot function to return a promise.

**Comment by jeanduplessis** [comment]
Scratch that - our issue was caused by something else.

**Comment by Robdel12** [comment]
Taken care of with #163 (v2) 🎉
